#define CMD_SET_MOTOR_A_TICKSSPEED (1)
#define CMD_SET_MOTOR_B_TICKSSPEED (2)

#define PID_DIVISION_FACTOR (1000.0)

#define CMD_SET_MOTOR_A_KP   (4)
#define CMD_SET_MOTOR_A_KI   (5)
#define CMD_SET_MOTOR_A_KD   (6)

#define CMD_SET_PID_SAMPLETIME (7)

#define CMD_SET_MOTOR_B_KP   (8)
#define CMD_SET_MOTOR_B_KI   (9)
#define CMD_SET_MOTOR_B_KD   (10)

#define CMD_SET_SERVO_0_POSITION (12)

#define CMD_GET_MOTOR_A_DISTANCE (14)
#define CMD_GET_MOTOR_B_DISTANCE (15)

#define CMD_GET_DISTANCESENSOR_MEASURE (16)

#define CMD_GET_MOTOR_A_TICKSPEED (17)
#define CMD_GET_MOTOR_B_TICKSPEED (18)

#define CMD_GET_SAMPLETIME_TO_SMALL (19)

#define CMD_SET_MOVE_DISTANCE (20)

#define CMD_RESET_MOVE_DISTANCE (21)

#define CMD_GET_LAST_CYCLE_TIME (22)

#define CMD_RESET_ARDUINO (23)
