const CMD_SET_TYPE             = (0x40)  
const CMD_SET_TEST_VALUE       = (0x00)
const CMD_SET_MOVEMENT         = (0x01)
const CMD_SET_SERVO_1_POSITION = (0x02)
const CMD_SET_SERVO_2_POSITION = (0x03)
const CMD_SET_BATTERY_ALARM    = (0x04)
const CMD_SET_PID_P_LEVEL      = (0x05)
const CMD_SET_PID_I_LEVEL      = (0x06)
const CMD_SET_PID_D_LEVEL      = (0x07)
const CMD_SET_BALANCING_LEVEL  = (0x08)
const CMD_SET_DEADBAND_LEVEL   = (0x09)
const CMD_SET_DISTANCESENSOR   = (0x0A)
const CMD_SET_BALANCE_MODE     = (0x0B)
const CMD_SET_LIGHT            = (0x0C)

const CMD_GET_TYPE             = (0x80)
const CMD_GET_TEST_VALUE       = (0x00)
const CMD_GET_MOVEMENT         = (0x01)
const CMD_GET_SERVO_1_POSITION = (0x02)
const CMD_GET_SERVO_2_POSITION = (0x03)
const CMD_GET_BATTERY_ALARM    = (0x04)
const CMD_GET_PID_P_LEVEL      = (0x05)
const CMD_GET_PID_I_LEVEL      = (0x06)
const CMD_GET_PID_D_LEVEL      = (0x07)
const CMD_GET_BALANCING_LEVEL  = (0x08)
const CMD_GET_DEADBAND_LEVEL   = (0x09)
const CMD_GET_DISTANCESENSOR   = (0x0A)
const CMD_GET_BALANCE_MODE     = (0x0B)
const CMD_GET_LIGHT            = (0x0C)
const CMD_GET_BATTERY_LEVEL_H  = (0x0D)
const CMD_GET_BATTERY_LEVEL_L  = (0x0E)
const CMD_GET_ANGLE            = (0x0F)
const CMD_GET_ANGLE_ACC        = (0x10)
const CMD_GET_DISTANCE         = (0x11)
const CMD_GET_SERVO_1_MIN      = (0x12)
const CMD_GET_SERVO_1_MAX      = (0x13)
const CMD_GET_SERVO_2_MIN      = (0x14)
const CMD_GET_SERVO_2_MAX      = (0x15)


module.exports = {
    CMD_SET_TYPE: CMD_SET_TYPE,
    CMD_SET_TEST_VALUE: CMD_SET_TEST_VALUE,
    CMD_SET_MOVEMENT: CMD_SET_MOVEMENT,
    CMD_SET_SERVO_1_POSITION: CMD_SET_SERVO_1_POSITION,
    CMD_SET_SERVO_2_POSITION: CMD_SET_SERVO_2_POSITION,
    CMD_SET_BATTERY_ALARM: CMD_SET_BATTERY_ALARM,
    CMD_SET_PID_P_LEVEL: CMD_SET_PID_P_LEVEL,
    CMD_SET_PID_I_LEVEL: CMD_SET_PID_I_LEVEL,
    CMD_SET_PID_D_LEVEL: CMD_SET_PID_D_LEVEL,
    CMD_SET_BALANCING_LEVEL: CMD_SET_BALANCING_LEVEL,
    CMD_SET_DEADBAND_LEVEL: CMD_SET_DEADBAND_LEVEL,
    CMD_SET_DISTANCESENSOR: CMD_SET_DISTANCESENSOR, 
    CMD_SET_BALANCE_MODE: CMD_SET_BALANCE_MODE,
    CMD_SET_LIGHT: CMD_SET_LIGHT,

    CMD_GET_TYPE: CMD_GET_TYPE,
    CMD_GET_TEST_VALUE: CMD_GET_TEST_VALUE,
    CMD_GET_MOVEMENT: CMD_GET_MOVEMENT,
    CMD_GET_SERVO_1_POSITION: CMD_GET_SERVO_1_POSITION,
    CMD_GET_SERVO_2_POSITION: CMD_GET_SERVO_2_POSITION,
    CMD_GET_BATTERY_ALARM: CMD_GET_BATTERY_ALARM,
    CMD_GET_PID_P_LEVEL: CMD_GET_PID_P_LEVEL,
    CMD_GET_PID_I_LEVEL: CMD_GET_PID_I_LEVEL,
    CMD_GET_PID_D_LEVEL: CMD_GET_PID_D_LEVEL,
    CMD_GET_BALANCING_LEVEL: CMD_GET_BALANCING_LEVEL,
    CMD_GET_DEADBAND_LEVEL: CMD_GET_DEADBAND_LEVEL,
    CMD_GET_DISTANCESENSOR: CMD_GET_DISTANCESENSOR,
    CMD_GET_BALANCE_MODE: CMD_GET_BALANCE_MODE,
    CMD_GET_LIGHT: CMD_GET_LIGHT,
    CMD_GET_BATTERY_LEVEL_H: CMD_GET_BATTERY_LEVEL_H,
    CMD_GET_BATTERY_LEVEL_L: CMD_GET_BATTERY_LEVEL_L,
    CMD_GET_ANGLE: CMD_GET_ANGLE,
    CMD_GET_ANGLE_ACC: CMD_GET_ANGLE_ACC,
    CMD_GET_DISTANCE: CMD_GET_DISTANCE,
    CMD_GET_SERVO_1_MIN: CMD_GET_SERVO_1_MIN,
    CMD_GET_SERVO_1_MAX: CMD_GET_SERVO_1_MAX,
    CMD_GET_SERVO_2_MIN: CMD_GET_SERVO_2_MIN,
    CMD_GET_SERVO_2_MAX: CMD_GET_SERVO_2_MAX,
}