CMD_TYPE_SET_VALUE       = 0x10
CMD_TYPE_GET_VALUE       = 0x20

CMD_SET_TEST_VALUE       = (0x00)
CMD_SET_MOVEMENT         = (0x01)
CMD_SET_SERVO_1_POSITION = (0x02)
CMD_SET_SERVO_2_POSITION = (0x03)
CMD_SET_BATTERY_ALARM    = (0x04)
CMD_SET_PID_P_LEVEL      = (0x05)
CMD_SET_PID_I_LEVEL      = (0x06)
CMD_SET_PID_D_LEVEL      = (0x07)
CMD_SET_DISTANCESENSOR   = (0x08)
CMD_SET_ENABLE_BALANCE   = (0x09)
CMD_SET_LIGHT            = (0x0A)

CMD_GET_TEST_VALUE       = (0x00)
CMD_GET_BATTERY_LEVEL    = (0x01)
CMD_GET_ANGLE            = (0x02)
CMD_GET_ANGLE_ACC        = (0x03)
CMD_GET_DISTANCE         = (0x04)