#ifndef MOTORCONTROLLERCMD_H
#define MOTORCONTROLLERCMD_H

#define CMD_SET_MOTOR_A_KP   (4)
#define CMD_SET_MOTOR_A_KI   (5)
#define CMD_SET_MOTOR_A_KD   (6)

#define CMD_SET_PID_SAMPLETIME (7)

#define CMD_SET_MOTOR_B_KP   (8)
#define CMD_SET_MOTOR_B_KI   (9)
#define CMD_SET_MOTOR_B_KD   (10)
  
#define CMD_SET_SERVO_0_POSITION (12)

#define CMD_GET_MOTOR_A_DISTANCE (14)
#define CMD_GET_MOTOR_B_DISTANCE (15)

#define CMD_GET_DISTANCESENSOR_MEASURE (16)

#define CMD_GET_MOTOR_A_TICKSPEED (17)
#define CMD_GET_MOTOR_B_TICKSPEED (18)

#define CMD_GET_SAMPLETIME_TO_SMALL (19)
#define CMD_RETURN_NEGATIV_TEST (20)

#define CMD_GET_LAST_CYCLE_TIME (22)
#define CMD_SET_DIR_KP (23)
#define CMD_SET_DIR_KI (24)
#define CMD_SET_DIR_KD (25)

#define CMD_GET_MOVE_BY_DISTANCE (26)
#define CMD_SET_MOVE_BY_DISTANCE (27)
#define CMD_ADD_MOVE_BY_DISTANCE (28)
#define CMD_SET_DISTANCE (29)
#define CMD_SET_DIRECTION (30)
#define CMD_SET_ROTATION (31)
#define CMD_SET_SPEED (32)
#define CMD_RESET_MOTOR_DISTANCE (33)
#define CMD_GET_PORT_COUNT (34)
#define CMD_RESET_PORT_COUNT (35)

#ifndef RESPONSELENGTH
extern char ResponseLength[];
#else
char ResponseLength[] = {0,
0,//Not used
0,//Not used
0,//Not used
0,//CMD_SET_MOTOR_A_KP   (4)
0,//CMD_SET_MOTOR_A_KI   (5)
0,//CMD_SET_MOTOR_A_KD   (6)
0,//CMD_SET_PID_SAMPLETIME (7)
0,//CMD_SET_MOTOR_B_KP   (8)
0,//CMD_SET_MOTOR_B_KI   (9)
0,//CMD_SET_MOTOR_B_KD   (10)
0,//Not used
0,//CMD_SET_SERVO_0_POSITION (12)
0,//Not used
4,//CMD_GET_MOTOR_A_DISTANCE (14)
4,//CMD_GET_MOTOR_B_DISTANCE (15)
4,//CMD_GET_DISTANCESENSOR_MEASURE (16)
4,//CMD_GET_MOTOR_A_TICKSPEED (17)
4,//CMD_GET_MOTOR_B_TICKSPEED (18)
4,//CMD_GET_SAMPLETIME_TO_SMALL (19)
4,//CMD_RETURN_NEGATIV_TEST (20)
0,//CMD_ADD_DIR_DIST
4,//CMD_GET_LAST_CYCLE_TIME (22)
0,//CMD_SET_DIR_KP (23)
0,//CMD_SET_DIR_KI (24)
0,//CMD_SET_DIR_KD (25)
4,//CMD_GET_MOVE_BY_DIR_DISTANCE (26)
0,//CMD_SET_MOVE_BY_DIR (27)
0, //CMD_ADD_MOVE_BY_DISTANCE (28)
0, //CMD_SET_DIR_DISTANCE (29)
0, //CMD_SET_DIR_DIRECTION (30)
0, //CMD_SET_DIR_ROTATION (31)
0, //CMD_SET_DIR_SPEED (32)
0, //CMD_RESET_MOTOR_DISTANCE (33)
4, //CMD_GET_PORT_COUNT (34)
0, //CMD_RESET_PORT_COUNT (35)
0, //Not used
};
#endif

#endif //MOTORCONTROLLERCMD_H