#define ENCODER_LEFT_PIN_1 (50)
#define ENCODER_LEFT_PIN_2 (53)
#define ENCODER_RIGHT_PIN_1 (51)
#define ENCODER_RIGHT_PIN_2 (52)

#define MOTOR_LEFT_SPEED_PIN (2)
#define MOTOR_LEFT_CONTROL_PIN_1 (3)
#define MOTOR_LEFT_CONTROL_PIN_2 (4)

#define MOTOR_RIGHT_SPEED_PIN (7)
#define MOTOR_RIGHT_CONTROL_PIN_1 (5)
#define MOTOR_RIGHT_CONTROL_PIN_2 (6)
