#define ENCODER_LEFT_PIN_1 (50)
#define ENCODER_LEFT_PIN_2 (53)
#define ENCODER_RIGHT_PIN_1 (51)
#define ENCODER_RIGHT_PIN_2 (52)

#define MOTOR_LEFT_SPEED_PIN (20)
#define MOTOR_LEFT_CONTROL_PIN_1 (22)
#define MOTOR_LEFT_CONTROL_PIN_2 (24)

#define MOTOR_RIGHT_SPEED_PIN (30)
#define MOTOR_RIGHT_CONTROL_PIN_1 (26)
#define MOTOR_RIGHT_CONTROL_PIN_2 (28)
