#define SERVO_HORIZONTAL (0)
#define SERVO_VERTICAL   (1)
#define SEGWAY_ENABLED   (2)
#define SEGWAY_SPEED     (3)
#define SEGWAY_TURN      (4)

#define ANGLE_OFFSET     (0)
#define PID_ENCODER_A_P  (1)
#define PID_ENCODER_A_I  (2)
#define PID_ENCODER_A_D  (3)
#define PID_ENCODER_B_P  (4)
#define PID_ENCODER_B_I  (5)
#define PID_ENCODER_B_D  (6)
#define PID_GYRO_P       (7)
#define PID_GYRO_I       (8)
#define PID_GYRO_D       (9)
#define PID_SPEED_P     (10)
#define PID_SPEED_I     (11)
#define PID_SPEED_D     (12)

