#define DISTANCE_RESET (0)

#define SERVO_HORIZONTAL_BYTE        (0)
#define SERVO_VERTICAL_BYTE          (1)
#define SEGWAY_ENABLED_BYTE          (2)
#define SEGWAY_SPEED_BYTE            (3)
#define SEGWAY_TURN_BYTE             (4)
#define TEST_BYTE                    (5)
#define DISTANCE_SENSOR_ENABLE_BYTE  (6)
#define SERVO_SPEED_BYTE             (7)

#define ANGLE_OFFSET_SHORT      (0)
#define PID_ENCODER_A_SHORT     (1)
#define GYRO_MEASURE_SHORT      (2)
#define PID_ENCODER_B_SHORT     (4)
#define PID_GYRO_SHORT          (7)
#define PID_SPEED_SHORT        (10)
#define DISTANCE_MEASURE_SHORT (11)
#define DISTANCE               (13)
#define SPEED_CORR_LIMIT_SHORT (14)
#define SPEED_PID_LIMIT_SHORT  (15)
#define TEST_SHORT             (16)
