#define DISTANCE_RESET (0)

#define SERVO_HORIZONTAL_BYTE (0)
#define SERVO_VERTICAL_BYTE   (1)
#define SEGWAY_ENABLED_BYTE   (2)
#define SEGWAY_SPEED_BYTE     (3)
#define SEGWAY_TURN_BYTE      (4)

#define ANGLE_OFFSET_SHORT     (0)
#define PID_ENCODER_A_P_SHORT  (1)
#define PID_ENCODER_A_I_SHORT  (2)
#define PID_ENCODER_A_D_SHORT  (3)
#define PID_ENCODER_B_P_SHORT  (4)
#define PID_ENCODER_B_I_SHORT  (5)
#define PID_ENCODER_B_D_SHORT  (6)
#define PID_GYRO_P_SHORT       (7)
#define PID_GYRO_I_SHORT       (8)
#define PID_GYRO_D_SHORT       (9)
#define PID_SPEED_P_SHORT     (10)
#define PID_SPEED_I_SHORT     (11)
#define PID_SPEED_D_SHORT     (12)
#define DISTANCE              (13)
#define SPEED_CORR_LIMIT_SHORT (14)
#define SPEED_PID_LIMIT_SHORT  (15)

